platform :ios, '10.0'

use_frameworks!

target 'CloverConnector_Example' do

    # The queuePriority branch of our fork of the Starscream framework is required for reliable transport of large files
    # Defining it here in the PodFile overrides the podspec dependency, which isn't allowed to specify a specific location and branch
    pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream.git', :tag => '3.0.5'

  pod 'GoConnector', '3.3.11'


end
